---
title: "HousingPrice_Modeling"
author: "jianwen wu"
date: "5/2/2019"
output: html_document
---
```{r}
library(recipes)
library(olsrr)
```


```{r}
train_df <- read_csv("data/training.csv")

test_df <- read_csv("data/validation.csv")
```

```{r}
data_process <- function(data){
  
  #combine train and test ----
  #create factor ----
  
  df <- data %>%
      mutate(MSSubClass = as.factor(MSSubClass),
             OverallCond = as.factor(OverallCond),
             YrSold = as.factor(YrSold), 
             MoSold = as.factor(MoSold),
             OverallQual = as.factor(OverallQual))
  # fill na with none ----
  NA_cols_None <- c("PoolQC",
                    "MiscFeature",
                    "Alley",
                    "Fence",
                    "FireplaceQu",
                    "GarageType",
                    "GarageFinish",
                    "GarageQual",
                    "GarageCond",
                    "BsmtQual",
                    "BsmtCond",
                    "BsmtExposure",
                    "BsmtFinType1",
                    "BsmtFinType2",
                    "MasVnrType",
                    "MSSubClass")
  
  df[,NA_cols_None][is.na(df[,NA_cols_None])] <- "None"
  
  # fill na with median ----
  df <- df %>%
    group_by(Neighborhood) %>%
    mutate(LotFrontage = replace_na(LotFrontage, replace = median(LotFrontage, na.rm = T))) %>%
    ungroup()
  
  
  # fill na with 0 ----
  NA_cols_0 <- (c(
    "GarageYrBlt",
    "GarageArea",
    "GarageCars",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "BsmtFullBath",
    "BsmtHalfBath",
    "MasVnrArea"
  ))
  
  df[,NA_cols_0][is.na(df[,NA_cols_0])] <- 0
  
  #fill na with most frequently ----
  df <- df %>%
    mutate(Electrical = str_replace_na(string = Electrical, replacement = "SBrkr")) %>% 
    
    filter(GrLivArea < 4000) %>% 
    
    mutate(YearBuilt = ifelse(YearBuilt >= 1950, "New", "Old"),
           Log_Sales_Price = log(SalePrice))
  
  
  
  return(df)
}

train_df <- data_process(train_df)

```


```{r}
vars_selection <- function(data) {
  data %>%
    mutate(
      Total_Bathroom = BsmtFullBath + BsmtHalfBath + FullBath + HalfBath) %>% 
    
    select(
      GrLivArea, GarageArea, TotalBsmtSF, TotRmsAbvGrd, BedroomAbvGr,
      YearBuilt, ExterQual, Neighborhood, BldgType, OverallQual, 
      HeatingQC, Total_Bathroom, Log_Sales_Price)
      
}

train_model_df <- vars_selection(train_df) 


rej_obj <- recipe(Log_Sales_Price~., data = train_model_df) %>%
  step_dummy(all_nominal(), -OverallQual) %>%
  prep()


train_model_df_model <- bake(rej_obj, new_data = train_model_df)

```

