---
title: "HousingPrice_Modeling"
author: "jianwen wu"
date: "5/2/2019"
output: html_document
---

```{r, warning=F, message=F, echo=F}
library(recipes)
library(olsrr)
library(tidyverse)
```

```{r}
train_df <- read_csv("https://raw.githubusercontent.com/jianwenwu/glm-project/master/Data/training.csv")
test_df <- read_csv("https://raw.githubusercontent.com/jianwenwu/glm-project/master/Data/validation.csv")
```

### 1. Data Cleaning
```{r}

data_process <- function(data){
  
  #convert into factor
  df <- data %>%
      mutate(MSSubClass = as.factor(MSSubClass),
             OverallCond = as.factor(OverallCond),
             YrSold = as.factor(YrSold), 
             MoSold = as.factor(MoSold),
             OverallQual = as.factor(OverallQual))
  
  #fill NA's With None ----
  NA_cols_None <- c("PoolQC",
                    "MiscFeature",
                    "Alley",
                    "Fence",
                    "FireplaceQu",
                    "GarageType",
                    "GarageFinish",
                    "GarageQual",
                    "GarageCond",
                    "BsmtQual",
                    "BsmtCond",
                    "BsmtExposure",
                    "BsmtFinType1",
                    "BsmtFinType2",
                    "MasVnrType",
                    "MSSubClass")
  
  df[,NA_cols_None][is.na(df[,NA_cols_None])] <- "None"
  
  #fill NA's with median of LotFrontage of Neighborhood ----
  df <- df %>%
    group_by(Neighborhood) %>%
    mutate(LotFrontage = replace_na(LotFrontage, replace = median(LotFrontage, na.rm = T))) %>%
    ungroup()
  
  
  #fill NA's with 0 ----
  NA_cols_0 <- (c(
    "GarageYrBlt",
    "GarageArea",
    "GarageCars",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "BsmtFullBath",
    "BsmtHalfBath",
    "MasVnrArea"
  ))
  
  df[,NA_cols_0][is.na(df[,NA_cols_0])] <- 0
  
  #fill NA's with most frequently appear ----
  df <- df %>%
    mutate(Electrical = str_replace_na(string = Electrical, replacement = "SBrkr")) %>% 
  #filter outlier ----  
    filter(GrLivArea < 4000) %>% 
          
    mutate(
      #Create New Variable for YearBuilt ----
      YearBuilt = ifelse(YearBuilt >= 1950, "New", "Old"),
      #Transform SalePrice into LogSalePrice ----
      Log_Sales_Price = log(SalePrice),
      #Create New Variable for TotalBathroom ----
      Total_Bathroom = BsmtFullBath + BsmtHalfBath + FullBath + HalfBath) %>%
    
    select(
      GrLivArea, GarageArea, TotalBsmtSF, TotRmsAbvGrd, BedroomAbvGr,
      YearBuilt, ExterQual, Neighborhood, BldgType, OverallQual, 
      HeatingQC, Total_Bathroom, Log_Sales_Price)
    
  return(df)
    
}

# run data_process function on train data
train_processed <- data_process(train_df)



#create dummy variables for all the nominal variables except variable "overallQual"
rej_obj <- recipe(Log_Sales_Price~., data = train_processed) %>%
  step_dummy(all_nominal(), -OverallQual) %>%
  prep()

#summary(rej_obj)

train_processed_model <- bake(rej_obj, new_data = train_processed)


glimpse(train_processed_model)

cor(train_processed %>%
      select_if(is.numeric))
```

### 2. Modeling

##### 2.1 Fit Linear Model on all 43 Variables against Log SalePrice
```{r}
lm_fit <- lm(Log_Sales_Price ~., data = train_processed_model) 

lm_fit %>%
  summary() %>%
  pander::pander()

```


##### 2.2  Forward Selection with AIC
```{r}
lm_fw_aic <- ols_step_forward_aic(lm_fit)

lm_fw_aic

#plot the number of variables vs Adj R2
tibble(number_of_variable = 1:27,
       adj_r2 = lm_fw_aic$arsq) %>%
  ggplot(aes(number_of_variable, adj_r2)) +
  geom_point() +
  geom_line() +
  labs(x = "Number of Variables", y = "Adjust R2") +
  scale_x_continuous(breaks = c(seq(1,27,1))) +
  geom_vline(xintercept  = 17, color = "red") +
  geom_text(data = tibble(number_of_variable = 1:27,
       adj_r2 = lm_fw_aic$arsq) %>%
         filter(number_of_variable == 17), aes(number_of_variable, label = "0.87672"), vjust = -1 ) + theme_bw() 
```

```{r}
test_processed <- data_process(test_df)

test_processed_model <- bake(rej_obj, new_data = test_processed)

 

```


