---
title: "Housing Price"
author: "jianwen wu"
date: "4/27/2019"
output: html_document
---

123

```{r Load Libraries}
library(tidyverse)
library(h2o)

h2o.init(max_mem_size = "4g")
```


```{r Import the data}
train_df <- read_csv("data/training.csv")

test_df <- read_csv("data/validation.csv")
```

#1. Data Processing

```{r str of data}

map(
  train_df, .f = function(x){
    class(x)
  }
) %>% 
  as_tibble() %>%
  gather()

```


###1.1 working on numerical data
```{r numerical}
train_df %>%
  select_if(is.numeric) %>%
  select(-Id) %>%
  select(MSSubClass:TotalBsmtSF) %>%
  select_if(is.numeric) %>%
  plot_hist_facet(ncol = 4)

train_df %>%
  select_if(is.numeric) %>%
  select(-Id) %>%
  select(X1stFlrSF:Fireplaces) %>%
  select_if(is.numeric) %>%
  plot_hist_facet(ncol = 4)

train_df %>%
  select_if(is.numeric) %>%
  select(-Id) %>%
  select(GarageYrBlt:SalePrice) %>%
  select_if(is.numeric) %>%
  plot_hist_facet(ncol = 4)

```


We know there are many numerical variables are actually categorical variables. We need to transform those. Those are:

* MSSubClass
* OverallCond
* YrSold
* MoSold

```{r transform}
train_df %>%
  mutate(MSSubClass = as.factor(MSSubClass),
         OverallCond = as.factor(OverallCond),
         YrSold = as.factor(YrSold), 
         MoSold = as.factor(MoSold)) %>%
  select(MSSubClass, OverallCond, YrSold, MoSold) 


```

###1.2 working on categorical data

```{r Explore the data}

# check the No. of missing values in each variable
train_df %>%
  map(.f = function(x){
    sum(is.na(x))
  })  %>%
  as_tibble() %>%
  gather(key = "Varible", value =  "Number_of_Missing_Value") %>%
  arrange(desc(Number_of_Missing_Value)) %>%
  mutate(Percentage = round(Number_of_Missing_Value / nrow(train_df) * 100,3))

```


#2 Modeling
```{r}

train_df_trans <- train_df %>%
  mutate(MSSubClass = as.factor(MSSubClass),
         OverallCond = as.factor(OverallCond),
         YrSold = as.factor(YrSold), 
         MoSold = as.factor(MoSold)) %>%
  mutate_if(base::is.character, base::as.factor) %>%
  select(-Id)

train_df_trans_h2o <- as.h2o(train_df_trans)
Y <- "SalePrice"
X <- setdiff(names(train_df_trans_h2o), Y)
prices_auml <- h2o.automl(x = X,
                          y = Y, 
                          nfolds = 5, training_frame = train_df_trans_h2o, max_runtime_secs = 3600)


prices_auml@leaderboard
```

